---
- name: stop grafana
  ansible.builtin.systemd:
    name: grafana
    state: stopped

- name: fetch service facts
  ansible.builtin.service_facts:

- name: Ensure the port is accessible
  ansible.posix.firewalld:
    port: "{{ grafana_port }}/tcp"
    permanent: true
    state: disabled
  when: ansible_facts.services['firewalld.service']['state'] == "running"

- name: remove the systemd unit
  ansible.builtin.file:
    path: /etc/systemd/system/grafana.service
    state: absent

- name: remove the directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ grafana_config_dir }}"
    - "{{ grafana_data_dir }}"

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

