---
- name: Purge Prometheus instance
  hosts:
    - grafana
  gather_facts: no
  roles:
    - defaults
  vars_prompt:
    - name: ok_to_delete
      prompt: "You're about to purge the grafana instance on {{ groups['prometheus'][0] }}. Are you sure [no]?"
      private: no
  tasks:
    - block:
        - name: purge prometheus
          ansible.builtin.include_tasks: roles/prometheus/tasks/purge.yml
      when:
        - ok_to_delete|bool

