---
- name: Stat prometheus dir
  ansible.builtin.stat:
    path: "{{ prometheus_config_dir }}"
  register: dir

- name: populate prometheus.yml file
  ansible.builtin.template:
    src: roles/prometheus/templates/prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: nobody
    group: nobody
  when: dir.stat.exists and dir.stat.isdir

